### PR TITLE
create entries for empty subsections

### PR DESCRIPTION
**Pull request by akavel**

### CODE REVIEW

**Comment by speter** [comment]
Thanks for the pull-request! Before starting code review, I'd like to understand your intended use case. Based on your profile, I'm guessing that you intend to use this in your repo https://github.com/akavel/backer . If that is the case, I'd suggest that you use a multi-valued variable instead of / in addition to the subsections. For example:

```
[main]         ; or [backups]
backup = foo   ; mandatory names in multi-valued variable
backup = bar
backup = baz
[backup "bar"] ; optional values in optional subsections
as = foobar
```

This has two advantages:
- multi-valued variable retains the order of values
- works with current version of gcfg

I'm not strongly against changing the behavior for empty subsections, but for this specific case it doesn't seem like it would solve your problem anyway. (I am strongly against relying on the ordering of subsections though.)

**Comment by akavel** [comment]
Uh, wow, thanks for exploring the issue to the extent of finding and reading my code in the app!

So, there are a few aspects to that:
1. After reading your alternative proposal, it now seems a quite acceptable compromise actually. That said, it does have some disadvantages for me:
   1. It adds repetition: the values are actually more like "c:/foo/bar/baz/bang/My Documents/blang", so I have to type it twice:
      
      ```
      [Main]
      backup = "c:/foo/bar/baz/bang/My Documents/blang"
      backup = "c:/aslkdf/yadoyu/uosf/Program Files/asdasdfsd"
      backup = "c:/uwevraiwe/My Foobars/Important Docs/asdfalshdfjlas"
      [Backup "c:/foo/bar/baz/bang/My Documents/blang"]
      as = "2015 Summer Stuff"
      ```
   2. As the example above shows, this also makes it significantly harder to verify that the quoted strings match (and a mismatch would need to be handled in some special way), and which one is which.
   3. I'm not that happy that parts of the information are now in two places: order is in one place, alias (_as_) is in another one, somewhat far away.
   4. That said, I believe it _is_ an acceptable compromise, and I'd strongly consider using it if it occurred to me earlier.
2. One thing quite important to me, is that I was actually very surprised that the subsections didn't get inserted into the map. I 100% expected they would. This I believe makes it worthy of some further consideration, as it's possible more people may get hit by that. They _are_ actually there, in the file, so losing them in translation was counterintuitive for me.
3. After implementing this PR, I did actually get hit by the randomization too, and that was also not something I consciously anticipated. But in the end I found it acceptable enough; also, now I think if I really need the ordering, I can add some additional attribute like "priority = high" or something.

By the way, I'm absolutely not insisting that my implementation is necessarily a good approach. But I wanted to try if I could do it quickly, and it worked, so I thought I could share, to signal my problem and so that you could at least have opportunity to decide if you find it fits your vision.

All that said, I want to take this opportunity to say that I like your library very much, and also we're happily using it internally in a product, and I find the format very nice and well readable. Thanks! :) One other thing I'd like, by the way, would be if it was easier to extend with additional deserialization formats (esp. for time.Time), but that's totally another story and OT here ;) sorry :P

**Comment by speter** [comment]
Thanks for the more realistic examples! I see now how splitting the configuration as I suggested can be cumbersome in your case. And you're also right that not creating the map entries is surprising to users, so implementing your suggestion seems an overall enhancement.

Regarding the implementation, passing an empty string for "name" as a sentinel value as you did is a reasonable trick, but it's hard to guess the purpose by just looking at the code. Could you add some brief explanatory comment at both the caller (`set(...)`) and the callee site (`return`)?

**Comment by akavel** [comment]
Please take another look.

**Pull request merged**
